### PR TITLE
Add visualisation for average temperature of India

### PR DESCRIPTION
**Pull request by pani-vishal**
#4 
I could only find seasonal and annual average temperatures from 1901 to 2012.
This data set is [used](https://data.gov.in/catalog/annual-and-seasonal-mean-temperature-india).
dataviz

### CODE REVIEW

**Comment by mubaris** [comment]
Looks Good. Few Changes

* Use `ggplot` style
* Use Plasma colormap

**Comment by pani-vishal** [comment]
On it.

**Comment by pani-vishal** [comment]
I this fine? Or should I change the grid dimensions?
ggplot

**Comment by mubaris** [comment]
Remove the grids and push the code

**Comment by mubaris** [comment]
Add this README.md like the previous ones. Otherwise full points will not be awarded

**Pull request merged**
