### PR TITLE
Added more opencode18 visulizations

### PR DESCRIPTION
**Pull request by Jigar3**
@gauthamzz  please review

### CODE REVIEW

**Review by Anupam-dagar — APPROVED** [review]

**Comment by Anupam-dagar** [comment]
You included mentors commit too but still Amazing work
merging

**Comment by Anupam-dagar** [comment]
@gauthamzz see

**Comment by Jigar3** [comment]
Are there points to share this on social :p

**Comment by Anupam-dagar** [comment]
Nah bro, leave that to us, we will do that in a pretty good way 😛

**Pull request merged**
