### PR TITLE
opencode data visulization part-2

### PR DESCRIPTION
**Pull request by Jigar3**
Visulized points Category in OpenCode Collab
@gauthamzz  please review

### CODE REVIEW

**Comment by gauthamzz** [comment]
@anupam-Dagar use both of the images at the end of the event and make a post on social media of the page :smile: this is great stuff

**Comment by Anupam-dagar** [comment]
@gauthamzz roger that :stuck_out_tongue_winking_eye:  :smile: 
we need more of this :stuck_out_tongue:

**Comment by Jigar3** [comment]
@Anupam-dagar  idea do main kar dunga

**Comment by Jigar3** [comment]
Kaunse data ka banao

**Comment by Anupam-dagar** [comment]
tum dhundho :stuck_out_tongue:

**Comment by gauthamzz** [comment]
Compare last year opencode and this year. 

Number of lines added per user 
Programming language in each repo vs total lines 
A graph which shows consistency of each participant 

It would be great if we had a plot with all repos in opencode.

**Comment by Jigar3** [comment]
On it

**Pull request merged**
